name: self hosted


#. When does it execute in jenkins?
on:
  push:
    branches:
      - test-selfhosted
  pull_request:
    branches:
      - main/*
  workflow_dispatch:
    inputs:
      review-api-url:
        description: 'Review_API_URL'
        required: true
        default: 'localhost'
        type: choice
        options:
          - 'localhost:3000'
          - '192.168.56.110:3000'

jobs:
  build-deploy-branch:
    runs-on: vbox-yusuf-local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test ls
        run: echo ls
      - name: test dockerver
        run: docker version
