name: self hosted

on:
  workflow_dispatch:
    inputs:
      deployType:
        description: 'Deploying Manual'
        required: true
        default: 'staging' 
        type: choice
        options:
        - staging
        - prod

jobs:
  build-deploy-branch:
    runs-on: vbox-yusuf-local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test ls
        run: echo ls
      - name: test dockerver
        run: docker version
