name: self hosted

env:
  AvailabiltyTimeInMinutes: 1
#. When does it execute in jenkins?
on:
  workflow_dispatch:
    inputs:
      review-api-url:
        description: 'Review_API_URL'
        required: true
        default: 'localhost'
        type: choice
        options:
          - 'localhost:3000'
          - '192.168.56.110:3000'

jobs:
  build-deploy-branch:
    runs-on: vbox-yusuf-local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test ls
        run: echo ls
      - name: test dockerver
        run: docker version
      - name: removing any docker related
        continue-on-error: true
        run: |
          docker stop `docker ps | grep whoami | awk '{ print $1 }'`
          docker image rm -f `docker images | grep whoami  | awk '{ print $3 }'`
          docker system prune -f --volumes
      - name: "Set job env from global env"
        run: |
          echo "Timeout_Minutes=$AvailabiltyTimeInMinutes" &gt;&gt; $GITHUB_ENV
      
      - name: no timeout
        id: rundocker
        timeout-minutes: 1
        continue-on-error: true
        run: |
          echo "the url will be available for ${{ jobs.build-deploy-branch.steps.rundocker.timeout-minutes }}"
          docker run -p 3000:8000 --rm --name whoami jwilder/whoami
      - name: test url
        run: echo "{{ github.event.inputs.review-api-url }}"
      - name: cleaning up the job
        run: docker rm -f whoami
