name: self hosted
env:
  TimeHosted: 1
#. When does it execute in jenkins?
on:
  workflow_dispatch:
    inputs:
      review-api-url:
        description: 'Review_API_URL'
        required: true
        default: 'localhost'
        type: choice
        options:
          - 'localhost:3000'
          - '192.168.56.110:3000'
      TTL_MINUTES:
        description: 'Time for instance to live (minutes)'
        required: true
        default: '30'
        type: number

jobs:
  build-deploy-branch:
    runs-on: vbox-yusuf-local
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: test ls
        run: echo ls
      - name: test dockerver
        run: docker version
      - name: removing any docker related
        continue-on-error: true
        run: |
          docker stop `docker ps | grep whoami | awk '{ print $1 }'`
          docker image rm -f `docker images | grep whoami  | awk '{ print $3 }'`
          docker system prune -f --volumes
      - name: no timeout
        id: rundocker
        continue-on-error: true
        run: |
          echo "the url will be available for ${{ github.event.inputs.TTL_MINUTES }} minute(s)"
          echo "${{ github.event.inputs.review-api-url }}"
          timeout ${{ github.event.inputs.TTL_MINUTES }} docker run -p 3000:8000 --rm --name whoami jwilder/whoami
      - name: cleaning up the job
        run: docker rm -f whoami
