name: publish-branch-build


#. When does it execute in jenkins?
on:
  push:
    tags:
      - v1.**
jobs:
  build_and_push_ui_base:
    runs-on: ubuntu-latest-aws
    steps: 
      - name: checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
