name: test sanity

#. When does it execute in jenkins?
on:
  pull_request:
    types: 
      - opened
    branches:
      - main

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: just listing
        run: ls -lah
