name: Test 3 jobs

on:
  workflow_dispatch:
    inputs:
      skip-jobs:
        description: 'SKIP JOB 2'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      build-type:
        description: 'build-type'
        required: true
        default: 'notbuild'
        type: choice
        options:
          - 'build'
          - 'buildAndDeploy'
          - 'notbuild'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: running job1
        run: echo "Running JOb 1"
  job2:
    runs-on: ubuntu-latest
    if: github.event.inputs.skip-jobs == 'no'
    needs: job1
    steps: 
      - name: running job2
        run: echo "Running JOb 2"
      #- name: Try to fail
      #  run: exit 1

  job3:
    runs-on: ubuntu-latest
    needs: [job1,job2]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') && (${{ inputs.build-type == 'build' ||  inputs.build-type == 'buildAndDeploy' }})
    steps: 
      - name: running job3
        run: echo "Running JOb 3"