name: testbuild
on:
  # run it on push to the default repository branch
  push:
    branches: [testnodejs]
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  pull-and-push:
    name: Pull from dockerhub and push to ecr
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: install dep
        id: runinstall
        run: npm ci
      
      - name: check the result
        run: |
          echo -e ${{ runinstall.outputs }}
          echo -e "####################################"
          echo -e ${{ runinstall.outputs.errors }}
